#!/usr/bin/env python3
"""Pack the STS1000 operator SPA into the form the device serves.

Reads the SPA source files, gzips each one deterministically at maximum
compression, and emits two things:

  <out>/lfs/www/<name>.gz      the tree the device serves from /lfs/www
  <out>/lfs/www/manifest.json  {name, content_type, size, gzip_size, sha256, etag}
  <out>/sts_webfs_assets.h     a C header with the same bytes compiled in

The /lfs/www tree is the normal path: the SPA lives on the SPI-NOR LittleFS
volume and is replaced without rebuilding firmware.  The generated C header is
a FALLBACK only, for a caller that chooses to compile the bundle into the
image (for example a recovery build that must serve a UI before the filesystem
mounts).  Nothing includes it automatically.

stdlib only - no third-party modules, no network access.  Output is
byte-for-byte reproducible: gzip mtime is pinned to 0 and the manifest keys are
sorted, so re-running without source changes rewrites identical files.
"""

import argparse
import gzip
import hashlib
import io
import json
import pathlib
import sys

DEFAULT_ASSETS = ["index.html", "app.css", "app.js"]

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".txt": "text/plain; charset=utf-8",
    ".woff2": "font/woff2",
}

HEADER_GUARD = "STS1000_ZEPHYR_NET_STS_WEBFS_ASSETS_H_"
DEFAULT_MAX_BYTES = 262144


def content_type(name):
    """Content-Type for an asset, by extension."""
    return CONTENT_TYPES.get(pathlib.PurePosixPath(name).suffix.lower(),
                             "application/octet-stream")


def c_symbol(name):
    """A C identifier fragment derived from an asset name."""
    out = []
    for ch in name:
        out.append(ch if (ch.isalnum() and ch.isascii()) else "_")
    sym = "".join(out)
    if sym and sym[0].isdigit():
        sym = "_" + sym
    return sym


def c_string(text):
    """Escape a Python str for use inside a C string literal."""
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "?":
            # Defuse trigraphs; harmless everywhere else.
            out.append("\\?")
        elif 0x20 <= ord(ch) < 0x7F:
            out.append(ch)
        else:
            # Non-ASCII would depend on the compiler's source charset.
            out.extend("\\%03o" % b for b in ch.encode("utf-8"))
    return "".join(out)


def gzip_bytes(raw):
    """Deterministic maximum-compression gzip of `raw`.

    mtime=0 and an explicit empty filename keep the header stable so the
    output hash only changes when the input does.
    """
    buf = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=buf,
                       compresslevel=9, mtime=0) as gz:
        gz.write(raw)
    return buf.getvalue()


def build_asset(src_dir, name):
    path = src_dir / name
    raw = path.read_bytes()
    gz = gzip_bytes(raw)
    digest = hashlib.sha256(raw).hexdigest()
    return {
        "name": name,
        "content_type": content_type(name),
        "size": len(raw),
        "gzip_size": len(gz),
        "sha256": digest,
        # ETag is quoted per RFC 9110 and derived from the UNCOMPRESSED bytes,
        # so it does not change if the compressor does.
        "etag": '"%s"' % digest[:16],
        "_gz": gz,
    }


def write_if_changed(path, data):
    """Write only when the content differs, so the packer is idempotent."""
    if path.exists() and path.read_bytes() == data:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return True


def render_header(assets):
    out = []
    a = out.append
    a("/* Generated by pack_assets.py - do not edit.\n")
    a(" *\n")
    a(" * FALLBACK ONLY.  The device normally serves the SPA from the /lfs/www\n")
    a(" * LittleFS tree; compile this header in only when an image must serve\n")
    a(" * the UI without a mounted filesystem.  Byte arrays are gzip streams:\n")
    a(" * serve them with Content-Encoding: gzip.\n")
    a(" */\n")
    a("#ifndef %s\n" % HEADER_GUARD)
    a("#define %s\n\n" % HEADER_GUARD)

    for asset in assets:
        gz = asset["_gz"]
        a("/* %s: %u raw -> %u gzip, sha256 %s */\n"
          % (asset["name"], asset["size"], asset["gzip_size"], asset["sha256"]))
        a("static const unsigned char sts_web_asset_%s[] = {\n"
          % c_symbol(asset["name"]))
        for i in range(0, len(gz), 12):
            chunk = gz[i:i + 12]
            a("\t" + " ".join("0x%02x," % b for b in chunk) + "\n")
        a("};\n\n")

    a("typedef struct {\n")
    a("\tconst char *path;\n")
    a("\tconst char *content_type;\n")
    a("\tconst unsigned char *gz;\n")
    a("\tunsigned int gz_len;\n")
    a("\tconst char *etag;\n")
    a("} sts_web_asset_t;\n\n")

    a("static const sts_web_asset_t sts_web_assets[] = {\n")
    for asset in assets:
        sym = c_symbol(asset["name"])
        a("\t{ \"/%s\", \"%s\", sts_web_asset_%s, %uU, \"%s\" },\n"
          % (c_string(asset["name"]), c_string(asset["content_type"]), sym,
             asset["gzip_size"], c_string(asset["etag"])))
    a("};\n\n")
    a("#define STS_WEB_ASSET_COUNT %u\n\n" % len(assets))
    a("#endif /* %s */\n" % HEADER_GUARD)
    return "".join(out).encode("ascii")


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n")[0],
        epilog="The /lfs/www tree is the normal delivery path. The emitted "
               "sts_webfs_assets.h is a FALLBACK that is only used if the "
               "caller chooses to compile it in; nothing includes it "
               "automatically.",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", type=pathlib.Path, default=None,
                    help="source directory (default: this script's directory)")
    ap.add_argument("--out-dir", type=pathlib.Path, default=None,
                    help="output directory (default: <src>/build)")
    ap.add_argument("--assets", nargs="+", default=None,
                    metavar="NAME",
                    help="asset file names to pack (default: %s)"
                         % " ".join(DEFAULT_ASSETS))
    ap.add_argument("--max-bytes", type=int, default=DEFAULT_MAX_BYTES,
                    help="fail if the total gzip size exceeds this "
                         "(default: %d)" % DEFAULT_MAX_BYTES)
    args = ap.parse_args(argv)

    src = (args.src or pathlib.Path(__file__).resolve().parent).resolve()
    out = (args.out_dir or (src / "build")).resolve()
    names = args.assets or DEFAULT_ASSETS

    missing = [n for n in names if not (src / n).is_file()]
    if missing:
        sys.stderr.write("error: missing asset(s) in %s: %s\n"
                         % (src, ", ".join(missing)))
        return 2

    assets = [build_asset(src, n) for n in names]

    www = out / "lfs" / "www"
    written = 0
    for asset in assets:
        if write_if_changed(www / (asset["name"] + ".gz"), asset["_gz"]):
            written += 1

    manifest = {
        "assets": [
            {k: a[k] for k in
             ("name", "content_type", "size", "gzip_size", "sha256", "etag")}
            for a in assets
        ],
        "total_size": sum(a["size"] for a in assets),
        "total_gzip_size": sum(a["gzip_size"] for a in assets),
    }
    manifest_bytes = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    if write_if_changed(www / "manifest.json", manifest_bytes):
        written += 1

    if write_if_changed(out / "sts_webfs_assets.h", render_header(assets)):
        written += 1

    total_raw = manifest["total_size"]
    total_gz = manifest["total_gzip_size"]

    name_w = max([len("asset")] + [len(a["name"]) for a in assets])
    print("%-*s %10s %10s %7s  %s"
          % (name_w, "asset", "raw", "gzip", "ratio", "etag"))
    print("-" * (name_w + 43))
    for a in assets:
        ratio = (a["gzip_size"] / a["size"] * 100.0) if a["size"] else 0.0
        print("%-*s %10d %10d %6.1f%%  %s"
              % (name_w, a["name"], a["size"], a["gzip_size"], ratio, a["etag"]))
    print("-" * (name_w + 43))
    ratio = (total_gz / total_raw * 100.0) if total_raw else 0.0
    print("%-*s %10d %10d %6.1f%%" % (name_w, "total", total_raw, total_gz, ratio))
    print()
    print("output tree   : %s" % www)
    print("fallback hdr  : %s" % (out / "sts_webfs_assets.h"))
    print("files updated : %d" % written)
    print("gzip total    : %d bytes (%.1f KiB) of %d limit (%.1f%% used)"
          % (total_gz, total_gz / 1024.0, args.max_bytes,
             total_gz / args.max_bytes * 100.0))

    if total_gz > args.max_bytes:
        sys.stderr.write("error: gzip total %d exceeds --max-bytes %d\n"
                         % (total_gz, args.max_bytes))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
